import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { TopLoaderBarProvider } from "@/providers/toploaderbar-provider";
import { Toaster } from "@/components/ui/sonner";
import TanstackProvider from "@/providers/tanstack-provider";

const quicksand = Quicksand({
  weight: ["300", "400", "700", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "CordXplorer",
    template: "%s | CordXplorer",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="min-w-[300px] subpixel-antialiased"
    >
      <body className={quicksand.className} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          <TopLoaderBarProvider>
            <Toaster position="top-right" duration={2000} />
            <SessionProvider>
              <TanstackProvider>{children}</TanstackProvider>
            </SessionProvider>
          </TopLoaderBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
